name: Build and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures a full clone for better analysis

      # Step 2: Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Step 3: Install and Run Trivy for File System Scan
      - name: Install and Run Trivy for FS Scan
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release

          # Add Trivy GPG key and repository
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list

          # Update package list and install Trivy
          sudo apt-get update
          sudo apt-get install -y trivy

          # Scan the current directory
          trivy fs .

      # Step 4: Docker Build and Push
      - name: Docker Build and Push
        run: |
          # Build and push Docker image
          docker build --build-arg TMDB_V3_API_KEY=f3709a71803ec3f4047f279972929ce6 -t netflix .
          docker tag netflix pavan9505/netflix1:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push pavan9505/netflix1:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    needs: build-analyze-scan
    runs-on: [aws-netflix]
    steps:
      # Step 1: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Step 2: Pull the Docker Image
      - name: Pull the Docker Image
        run: docker pull pavan9505/netflix1:latest

      # Step 3: Trivy Image Scan
      - name: Trivy Image Scan
        run: trivy image pavan9505/netflix1:latest

      # Step 4: Run the Container
      - name: Run the Container Netflix
        run: docker run -d --name netflix -p 8081:80 pavan9505/netflix:latest
